name: didyoucodetoday
description: DID YOU CODE TODAY?

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  bloc: ^8.1.2
  crypto: ^3.0.3
  elegant: ^0.0.3
  flutter:
    sdk: flutter
  flutter_appauth: ^6.0.2
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  get_it: ^7.6.4
  go_router: ^12.0.0
  google_fonts: ^6.1.0
  rxdart: ^0.27.7
  secretary: ^1.0.1
  supabase_flutter: ^1.10.22

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env